### ISSUE TITLE
Update how to use 

### ISSUE THREAD

**Issue by rajadilipkolli** [gavlyukovskiy/spring-boot-data-source-decorator#1]
Can you please update in readMe.md how to use this in spring-boot projects out of the box. I am eagerly looking at one such approach to use datasource-decorator

**Comment by gavlyukovskiy** [comment]
Hi, I'm in the middle of changing api a little bit,
After I will publish release into maven repository, I have never done this before, any advice is appreciated.

**Comment by gavlyukovskiy** [comment]
If you want give it a try please clone repository, run `gradlew clean build install` and add dependency
  <groupId>com.github.gavlyukovskiy</groupId>
  <artifactId>decorator-spring-boot-autoconfigure</artifactId>
  <version>1.0-RELEASE</version>
if you already have any proxy library, if you don't I'd recomment you to use p6spy-spring-boot-starter

**Comment by rajadilipkolli** [comment]
[this](https://github.com/spring-projects/spring-social-github/blob/master/publish-maven.gradle) might help you

**Comment by gavlyukovskiy** [comment]
I published all artifacts into Maven Central, you can add one of starters. Now you can play with it :)

For now only wrapping is done on library side, it means you will get only basics of each library. 
P6Spy does not have ability to register modules at runtime, but supports ServiceLoaders. I'm not sure about others.

If you have any suggestions to make it more clear or some use case I'll be glad to add them to the guide.
