### ISSUE TITLE
ClassNotFoundException found for DataSourcePoolMetadata in Springboot 2.0.0.RC2

### ISSUE THREAD

**Issue by cyberoblivion** [gavlyukovskiy/spring-boot-data-source-decorator#11]
When including below dependency in my springboot application I get a ClassNotFoundException. 
```
        <dependency>
            <groupId>com.github.gavlyukovskiy</groupId>
            <artifactId>datasource-proxy-spring-boot-starter</artifactId>
            <version>1.3.2</version>
        </dependency>
```

Looks like DataSourcePoolMetadata moved from
org.springframework.boot.autoconfigure.jdbc.metadata.DataSourcePoolMetadata
to
org.springframework.boot.jdbc.metadata.DataSourcePoolMetadataProvider

Are there plans for a Springboot 2 compatible version?

**Comment by gavlyukovskiy** [comment]
Hi, I'm planing to release compatible version next week.

**Comment by gavlyukovskiy** [comment]
Version 1.4.0 is synced to Maven Central.
