### ISSUE TITLE
Update to FlexyPool 3.0.2

### ISSUE THREAD

**Issue by oburgosm** [gavlyukovskiy/spring-boot-data-source-decorator#112]
FlexyPool 3 has breaking changes that made that spring-boot-data-source-decorator fail. It would be nice that this project update to FlexyPool 3.0.2:

https://github.com/vladmihalcea/flexy-pool/issues/73

**Comment by gavlyukovskiy** [comment]
@oburgosm fixed in https://github.com/gavlyukovskiy/spring-boot-data-source-decorator/pull/113 and released as [1.10.0](https://github.com/gavlyukovskiy/spring-boot-data-source-decorator/releases/tag/v1.10.0)
