### ISSUE TITLE
Is log4j2 supported by this integration?

### ISSUE THREAD

**Issue by Anydag** [gavlyukovskiy/spring-boot-data-source-decorator#12]

**Comment by gavlyukovskiy** [comment]
Hi, all proxy providers (p6spy, datasource-proxy and flexy-pool) are using slf4j by default, if you configured your spring boot application to use log4j2 everything should be fine.

**Comment by Anydag** [comment]
Hi Arthur,

It appeared that the logger name in log4j2.xml should be just "p6spy" and not the class name of an appender. Works like a charm now. Thank you.

**Comment by gavlyukovskiy** [comment]
I'm glad to hear you solved your issue. If you have any more questions feel free to open another issue.
