### ISSUE TITLE
multiline sql 

### ISSUE THREAD

**Issue by huashanyu** [gavlyukovskiy/spring-boot-data-source-decorator#14]
Why do you output two times SQL
for example：
p6spy   : #1524122276922 | took 663ms | statement | connection 4|SELECT * FROM XXX|SELECT * FROM XXX

**Comment by gavlyukovskiy** [comment]
As far as I remember this default format of p6spy - `MultiLineFormat` where first sql is with all bind variables (`?`) replaced by actual values and second is sql that actually send to the driver without parameters replacing.
You can change it by specifying property `decorator.datasource.p6spy.log-format` with custom logging format according to the [p6spy documentation](http://p6spy.readthedocs.io/en/latest/configandusage.html#customlogmessageformat).

For example
```
decorator.datasource.p6spy.log-format=%(currentTime) | took %(executionTime)ms | %(category) | connection %(connectionId) | %(sql)
```
will log only sql with actual values.

**Comment by Francisco-Castro** [comment]
Hi gavlyukovskiy,

I really admire your work, thank you so much for your contribution. 
I used to work in a company where I was fixing and featuring their software. One particular characteristics of this software was the possibility to print out on the console all the queries make into the database. Anyway, I am using your framework and I want to print out only the statement without the "commit" line. (Just the query) as is shown in the picture below. In another version it was possible using: 

`#excludecategories=info,debug,result,resultset,batch`

and include "commit" inside to exclude every commit.

Do you have any idea how can I do that?
<img width="1540" alt="Screen Shot 2019-10-12 at 5 35 42 PM" src="https://user-images.githubusercontent.com/47334502/66707956-07a81f00-ed17-11e9-80d3-d5e07423df1a.png">
