### ISSUE TITLE
"Tried to close span but it is not the current span" in transactions with several datasources

### ISSUE THREAD

**Issue by oburgosm** [gavlyukovskiy/spring-boot-data-source-decorator#15]
Hello.

I'm using datasource-decorator with datasource-proxy, sleuth and atomikos. I've verified that if I have two datasources in a XA transaction, the spans is not closing correctly. In logs I see the next trace:

 - 2018-05-22 10:18:15,785 [main] WARN  org.springframework.cloud.sleuth.util.ExceptionUtils - [data-framework-it-jta,5b03d224214b159527c66be694e13dfa,b3ea5e53e954cf35,2ab0b3ba30ec5b72,false] - Tried to close span but it is not the current span: [Trace: 5b03d224214b159527c66be694e13dfa, Span: 2ab0b3ba30ec5b72, Parent: 27c66be694e13dfa, exportable:false].  You may have forgotten to close or detach [Trace: 5b03d224214b159527c66be694e13dfa, Span: b3ea5e53e954cf35, Parent: 2ab0b3ba30ec5b72, exportable:false].

I think that the problem is in class TracingQueryExecutionListener. I start a transaction. TracingQueryExecutionListener create a new span for first connection, and later, create a second span for the second connection, which have as parent Span the span of connnection1. After, it close connection1, but it can't close span, because the current Span is the span of connection2.

**Comment by gavlyukovskiy** [comment]
Hi, thanks for reporting it, I was able to reproduce it in small test case and working on a fix.

**Comment by gavlyukovskiy** [comment]
Are you using version 1.3.2 or 1.4.0?

**Comment by oburgosm** [comment]
I'm using version 1.3.2

**Comment by gavlyukovskiy** [comment]
New version 1.3.3 is released, will be in Maven Central in few hours.

**Comment by oburgosm** [comment]
Great!! Thanks!!
