### ISSUE TITLE
Null pointer in case of scheduled jobs

### ISSUE THREAD

**Issue by iqbaldeep** [gavlyukovskiy/spring-boot-data-source-decorator#18]
I am working on v1.3.3 and using p6spy module with springboot 1.5.4. One of our scheduled jobs runs using `org.springframework.cloud.sleuth.instrument.async.LazyTraceExecutor` for tracing.

Whenever this job runs, there is a null pointer at `TracingJdbcEventListener.onAfterStatementClose():141` because `tracer.getCurrentSpan()` is null at this point. Would be good if there is a null check here before you do `currentSpan.getName()`

**Comment by gavlyukovskiy** [comment]
Hi, what do you have in this scheduled method? Can you provide sample code to reproduce the issue?
