### ISSUE TITLE
Upgrade to Sleuth 2.X

### ISSUE THREAD

**Issue by scassidy1986** [gavlyukovskiy/spring-boot-data-source-decorator#21]
Hey,

Are there any plans to upgrade to the latest version of spring-sleuth? At the minute the library does not appear to work due to some of the changes in sleuth/zipkin.

Cheers!

**Comment by gavlyukovskiy** [comment]
Hi, currently I'm migrating all listeners to brave (current tracing layer of sleuth) in corresponding branch. If you're willing to help you can try to build branch `brave` and do some tests. 
Yet I don't have any ETA on releasing it.

**Comment by gavlyukovskiy** [comment]
Closing in favor of #16.
