### ISSUE TITLE
p6spy-spring-boot-starter:1.4.3 with SpringBoot 2.0.4 fails with ArrayStoreException

### ISSUE THREAD

**Issue by bwilsonPaychex** [gavlyukovskiy/spring-boot-data-source-decorator#22]
I'm trying to use p6spy-spring-boot-starter with a spring boot 2.0.4 application however it fails almost immediately after startup with an array store exception. Googling around it seems like there may be changes needed to support spring boot 2 (spring cloud had to make similiar changes). I've attached the stack trace to this issue. Let me know if I can provide more details
[output.txt](https://github.com/gavlyukovskiy/spring-boot-data-source-decorator/files/2287137/output.txt)

**Comment by gavlyukovskiy** [comment]
Is problem disappear when you remove p6spy-starter? 
Looks like there is some problem with reading annotations, but I'm not sure it's related to starter itself, could you please provide minimal sample to reproduce the issue?

**Comment by gavlyukovskiy** [comment]
also please verify that you're using version 1.4.3 of the starter, only this one supports spring boot 2.

**Comment by bwilsonPaychex** [comment]
The problem does not happen as soon as I remove that dependency. I can verify that version 1.4.3 is the version I'm using that has the issue. I should be able to get a sample today

**Comment by bwilsonPaychex** [comment]
I've attached a sample. I had to remove some of the repo configuraiton as we have our internal servers so that might need to be added back but the basic application with the dependency fails the same way. Let me know if this isn't enough and I can provide more
[openshift-example.zip](https://github.com/gavlyukovskiy/spring-boot-data-source-decorator/files/2291589/openshift-example.zip)

**Comment by gavlyukovskiy** [comment]
Thanks for the sample, I was able to run it after uncommenting `version = projectVersion + '.' + version` and specifying `mavenCentral()` repository to download dependencies and plugins. 
But in my case application starts normally and I'm able to request `http://localhost:8080//rest/is/helloworld/1_0/greeting`.

Could you please check that nothing was changed/cached in your local project? I'm using jdk1.8.0_171.

**Comment by bwilsonPaychex** [comment]
Hmmm, unfortunately using mavenCentral directly is not an option for us, however this leads me to believe we have some internal dependency issues going on. I'll investigate some in the next day or so and comment. I really appreciate you taking a look into this.

**Comment by gavlyukovskiy** [comment]
I hope you resolved the issue, if you need any help feel free to reopen.
