### ISSUE TITLE
TracingQueryExecutionListener Order

### ISSUE THREAD

**Issue by oburgosm** [gavlyukovskiy/spring-boot-data-source-decorator#25]
I think it would be useful that TracingQueryExecutionListener bean had an Order with a high precedence.

I am using spring-boot-data-source-decorator 1.5.1 with datasource-proxy. I need to use my custom MethodExecutionListener.  Sometimes, depending on configuration order, my custom MethodExcecutionListener may be executed before the connection span has been created. 

Thanks in advance.

**Comment by gavlyukovskiy** [comment]
I think it's a good idea.
