### ISSUE TITLE
All requests as subspans with flyway enabled

### ISSUE THREAD

**Issue by tomorrow10** [gavlyukovskiy/spring-boot-data-source-decorator#26]
Hello, I have a simple spring boot application, where I connect to oracle and wanted to instrument the db communication. The db database model is maintained by flyway.

The instrumentation itself seems to be working ok, but there is one issue. All requests are paired to last log record acquired during the start of the application.

If I turn of flyway, everything works ok. I tried both p6spy and datasource proxy and they both have the same issue.

The flyway is configured with autoconfiguration of spring boot. However, the same problem appears, when I run the flyway migrate funcionality manually like this

```
@Bean
    fun flyway(
            dataSource: DataSource
    ): Flyway {
        val flyway = Flyway()
        flyway.dataSource = dataSource
        flyway.table = "flyway_schema_history"
        flyway.setLocations("classpath:db/migration")
        flyway.migrate()
        return flyway
    }
```

It's not problem of flyway, because without the instrumentation of db communication, the spanning works fine even with flyway enabled.

**Comment by gavlyukovskiy** [comment]
Fixed by #27.
