### ISSUE TITLE
Tracing : avoid some span to be exportable

### ISSUE THREAD

**Issue by chsi13** [gavlyukovskiy/spring-boot-data-source-decorator#34]
Hi.

I trace db statements with p6spy and spring cloud sleuth. It exports connection , query and fetch spans...Is it possible to only export to zipkin query statements ???

**Comment by gavlyukovskiy** [comment]
You can now use property
```
decorator.datasource.sleuth.include=query
```
to include only query spans.

**Comment by chsi13** [comment]
So great! Thank you great job 😉

**Comment by chsi13** [comment]
@gavlyukovskiy When do you plan to release new version with this enhancement ?

**Comment by gavlyukovskiy** [comment]
I'm planing to finish work on some enhancements in this release. I think it will be by the end of this week.

**Comment by gavlyukovskiy** [comment]
@chsi13 I released new version today. New version is 1.5.6, feel free to try it!

**Comment by chsi13** [comment]
Will try asap! Thanks
