### ISSUE TITLE
NPE v1.5.7

### ISSUE THREAD

**Issue by oburgosm** [gavlyukovskiy/spring-boot-data-source-decorator#36]
We have an application affected for this issue: https://github.com/gavlyukovskiy/spring-boot-data-source-decorator/issues/35.

Then, we updated to v1.5.7, but now, we have another similar exception:

java.lang.NullPointerException: null
        at com.github.gavlyukovskiy.cloud.sleuth.TracingListenerStrategy.**addQueryRowCount**(TracingListenerStrategy.java:66)
        at com.github.gavlyukovskiy.cloud.sleuth.TracingQueryExecutionListener.**afterQuery**(TracingQueryExecutionListener.java:59)
...

**Comment by gavlyukovskiy** [comment]
Hi @oburgosm, can you provide sample application (or at least connection pool and database you're using) to reproduce the issue? 
It looks like connection was closed at the time when statement was executed, but normally in this case `executeUpdate` would throw an exception instead of returning row count.

**Comment by oburgosm** [comment]
I would like to give you an example, but it's very difficult. We couldn't isolate the problem and the error occurs sometimes. I think probably the exception is masking another problem, but if we disabled datasource decorator, there is no error.

We are using Atomikos for connection pool and DB2 as database.

Thanks in advance.

**Comment by oburgosm** [comment]
Is there any news on this issue? Would it be possible to do the operation null safe, avoiding NullPointerException?

**Comment by gavlyukovskiy** [comment]
@oburgosm I couldn't reproduce the issue with your setup, but I added check for this specific scenario. Please test version 1.5.8 once available

**Comment by oburgosm** [comment]
@gavlyukovskiy , We tested it, and all it's ok :)
