### ISSUE TITLE
Add config to toggle on/off effective sql string when using p6spy

### ISSUE THREAD

**Issue by kevinjom** [gavlyukovskiy/spring-boot-data-source-decorator#38]
Currently, the sql statement added in the span is always [effective sql string](https://p6spy.readthedocs.io/en/latest/configandusage.html#logmessageformat), which has `?` replaced with real values when using prepared statement, it will be good if we can introduce a flag to switch between the raw query (with placeholders) and the resolved sql query with parameter values, because some people would prefer to not including all the values (especially confidential/pii data) in the spans.

I noticed the related code is at [TracingJdbcEventListener.java#L120](https://github.com/gavlyukovskiy/spring-boot-data-source-decorator/blob/master/datasource-decorator-spring-boot-autoconfigure/src/main/java/com/github/gavlyukovskiy/cloud/sleuth/TracingJdbcEventListener.java#L120), it should not be a big change, I would be more than happy to prepare a PR if you are happy with that.

**Comment by gavlyukovskiy** [comment]
Closed by #39
