### ISSUE TITLE
adding datasource-proxy-spring-boot-starter as maven dependency is throwing error

### ISSUE THREAD

**Issue by rajadilipkolli** [gavlyukovskiy/spring-boot-data-source-decorator#4]
adding below dependency is throwing error
```xml
                 <dependency>
			<groupId>com.github.gavlyukovskiy</groupId>
			<artifactId>datasource-proxy-spring-boot-starter</artifactId>
			<version>1.2.1</version>
		</dependency>
```
`The POM for com.github.gavlyukovskiy:datasource-decorator-spring-boot-autoconfigure:jar:1.2.1 is missing, no dependency information available`

**Comment by rajadilipkolli** [comment]
Issue is that 1.2.1 is not published to maven

https://mvnrepository.com/artifact/com.github.gavlyukovskiy/datasource-decorator-spring-boot-autoconfigure

**Comment by gavlyukovskiy** [comment]
Hi, thanks for raising this, looks like this one is not synchronized with Maven Central. 
I started synscronization, meanwhile you can try download it from jcenter.

**Comment by gavlyukovskiy** [comment]
Fixed now
