### ISSUE TITLE
Set the dataSourceName as remoteServiceName in TracingListenerStrategy

### ISSUE THREAD

**Issue by klu2** [gavlyukovskiy/spring-boot-data-source-decorator#59]
Right now, in our [Spring Sleuth Configuration](https://github.com/gavlyukovskiy/spring-boot-data-source-decorator#spring-cloud-sleuth) you are using the `dataSourceName`  in `TracingListenerStrategy.beforeGetConnection` only in the span name, but if you would also call `connectionSpan.setRemoteServiceName(dataSourceName)` then then database name would be sent to Zipkin as well and the database then would also be shown in the dependencies-view of Zipkin.

Same would need to be done in `beforeQuery` and `beforeResultSetNext`

This is how the brave-instrumentation library does exactly that job: https://github.com/openzipkin/brave/blob/master/instrumentation/p6spy/src/main/java/brave/p6spy/TracingJdbcEventListener.java#L118

**Comment by gavlyukovskiy** [comment]
Thank you for suggestion, I will make the change. 

Does it make sense to set it for `statement` and `fetch` spans as well?

**Comment by klu2** [comment]
I would say so, yes.

Thanks for your quick response!

**Comment by gavlyukovskiy** [comment]
@klu2 released in 1.7.1

**Comment by klu2** [comment]
awesome, thanks!
