### ISSUE TITLE
spy.log created when application stoped

### ISSUE THREAD

**Issue by ansurakin** [gavlyukovskiy/spring-boot-data-source-decorator#63]
Hello.
my pom.xml
`
<dependency>
            <groupId>com.github.gavlyukovskiy</groupId>
            <artifactId>p6spy-spring-boot-starter</artifactId>
            <version>1.7.1</version>
        </dependency>
`
application.properties
`
decorator.datasource.enabled=true
decorator.datasource.p6spy.logging=slf4j
`
By this "Name of log file to use (only with logging=file)." did I understand correctly: file wil not create if property decorator.datasource.p6spy.logging != file.
Why spy.log created when application stoped? I don't need this file. How resolve it?

**Comment by gavlyukovskiy** [comment]
Hi @ansurakin, you did understand it correctly, but unfortunately I cannot reproduce this behavior, please provide minimal sample project.
