### ISSUE TITLE
Add support for @DataJpaTest

### ISSUE THREAD

**Issue by simasch** [gavlyukovskiy/spring-boot-data-source-decorator#65]
Your starter is great but it doesn't work when using @DataJpaTest and also probably not with the other test slices (DataJdbcTest etc).

As most JPA tests are using @DataJpaTest it would be great if logging would be supported.

**Comment by gavlyukovskiy** [comment]
@simasch thanks for reporting. Does "not work" in sense that tests fail when you're using starter or that there is no query logging?

**Comment by simasch** [comment]
Sorry for being not enough precise. 
"Not work" means there is no logging happening. I assume that the proxy is not created

**Comment by gavlyukovskiy** [comment]
@simasch got you, thanks for the details. I looked only briefly, but I assume that @DataJpaTest imports specific set of auto-configurations and the one provided by this starter is not one of them. 
I think I can just add the auto-configuration to `org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase` in `spring.factories`, I'll try to check that this week as well as other issues.

**Comment by gavlyukovskiy** [comment]
I have published 1.8.0 that will seamlessly delegate decorating to Spring Cloud Sleuth. I have put some details regarding migration process and using it together with Spring Cloud Sleuth in the [README](https://github.com/gavlyukovskiy/spring-boot-data-source-decorator#spring-cloud-sleuth-deprecated).

**Comment by simasch** [comment]
Hi @gavlyukovskiy 
I tried 1.8.0, but I can't see any logging on a @DataJpaTest

You can reproduce the problem with my simple test project: https://github.com/simasch/datasource-decorator

**Comment by gavlyukovskiy** [comment]
@simasch thanks for providing an example, I will take a look

**Comment by gavlyukovskiy** [comment]
Hey @simasch, so I've tried your project locally and after changing version to 1.8.0 [here](https://github.com/simasch/datasource-decorator/blob/main/pom.xml#L32) (1.8.1 doesn't exist) I am able to see logs for both tests.
`EmployeeRepositoryIT#createAndFindAll`:
```
2022-01-17 23:33:30.996 DEBUG 12788 --- [           main] n.t.d.l.l.SLF4JQueryLoggingListener      : 
Name:dataSource, Connection:5, Time:0, Success:True
Type:Prepared, Batch:False, QuerySize:1, BatchSize:0
Query:["call next value for hibernate_sequence"]
Params:[()]
2022-01-17 23:33:31.027 DEBUG 12788 --- [           main] n.t.d.l.l.SLF4JQueryLoggingListener      : 
Name:dataSource, Connection:5, Time:15, Success:True
Type:Prepared, Batch:False, QuerySize:1, BatchSize:0
Query:["insert into employee (name, id) values (?, ?)"]
Params:[(Peter,1)]
2022-01-17 23:33:31.105 DEBUG 12788 --- [           main] n.t.d.l.l.SLF4JQueryLoggingListener      : 
Name:dataSource, Connection:6, Time:0, Success:True
Type:Prepared, Batch:False, QuerySize:1, BatchSize:0
Query:["select employee0_.id as id1_0_, employee0_.name as name2_0_ from employee employee0_"]
Params:[()]
```
`EmployeeRepositoryTest#createAndFindAll`:
```
2022-01-17 23:36:43.638  INFO 17312 --- [           main] o.s.t.c.transaction.TransactionContext   : Began transaction (1) <some more info here>
2022-01-17 23:36:43.772 DEBUG 17312 --- [           main] n.t.d.l.l.SLF4JQueryLoggingListener      : 
Name:dataSource, Connection:5, Time:0, Success:True
Type:Prepared, Batch:False, QuerySize:1, BatchSize:0
Query:["call next value for hibernate_sequence"]
Params:[()]
2022-01-17 23:36:43.780 DEBUG 17312 --- [           main] n.t.d.l.l.SLF4JQueryLoggingListener      : 
Name:dataSource, Connection:5, Time:0, Success:True
Type:Prepared, Batch:False, QuerySize:1, BatchSize:0
Query:["insert into employee (name, id) values (?, ?)"]
Params:[(Peter,1)]
2022-01-17 23:36:43.858 DEBUG 17312 --- [           main] n.t.d.l.l.SLF4JQueryLoggingListener      : 
Name:dataSource, Connection:5, Time:0, Success:True
Type:Prepared, Batch:False, QuerySize:1, BatchSize:0
Query:["select employee0_.id as id1_0_, employee0_.name as name2_0_ from employee employee0_"]
Params:[()]
2022-01-17 23:36:43.873  INFO 17312 --- [           main] o.s.t.c.transaction.TransactionContext   : Rolled back transaction <some more info here>
```

Am I missing something?

**Comment by simasch** [comment]
Hi @gavlyukovskiy 
Oh you are right! It works perfectly. Thank you
Sorry but I don't know why it didn't work on the first attempt. Probably because of the wrong version number.

**Comment by gavlyukovskiy** [comment]
I'm glad to hear that! 
Thanks for suggesting this feature, this was wonderful idea 👍

**Comment by simasch** [comment]
Thank you! 
The starter is perfect! Much better solution than Hibernates logging.
