### ISSUE TITLE
ExistingValue must be an instance of com.zaxxer.hikari.HikariDataSource

### ISSUE THREAD

**Issue by liuweiGL** [gavlyukovskiy/spring-boot-data-source-decorator#85]
Same like https://github.com/spring-cloud/spring-cloud-sleuth/issues/2096

**Comment by gavlyukovskiy** [comment]
Workaround is also the same, mentioned in my comment: https://github.com/spring-cloud/spring-cloud-sleuth/issues/2096#issuecomment-1009070889
