### ISSUE TITLE
sql cannot print

### ISSUE THREAD

**Issue by 9527dong** [gavlyukovskiy/spring-boot-data-source-decorator#90]
The jar package I use is:
```xml
        <dependency>
            <groupId>com.github.gavlyukovskiy</groupId>
            <artifactId>datasource-proxy-spring-boot-starter</artifactId>
            <version>1.8.1</version>
        </dependency>
```

My application.yml configuration is:
```xml
logging:
  level:
    net.ttddyy.dsproxy.listener.logging: DEBUG
```
But the sql is not printed in my logs, what is the reason?    

I am using spring data , spring boot version is 2.7.4.

**Comment by gavlyukovskiy** [comment]
@9527dong I'm afraid that's not enough information to help you. Most likely something is wrong with your logging configuration, with that I cannot help you.
