### ISSUE TITLE
Error when use org.springframework.jdbc.datasource.lookup.AbstractRoutingDataSource

### ISSUE THREAD

**Issue by Cekerel** [gavlyukovskiy/spring-boot-data-source-decorator#91]
My dataSource configuration
![image](https://github.com/gavlyukovskiy/spring-boot-data-source-decorator/assets/34343884/531d3afb-ff20-48b6-8d64-e10f480354cc)

The subclass of ***AbstractRoutingDataSource***
![image](https://github.com/gavlyukovskiy/spring-boot-data-source-decorator/assets/34343884/78cd8c49-6732-426e-bb59-eb0e9c2c0bd7)

After running the web application
![image](https://github.com/gavlyukovskiy/spring-boot-data-source-decorator/assets/34343884/64604501-d2c2-48fe-b1d7-a15f4c4eb14c)

**Comment by Cekerel** [comment]
Spring Boot 2.3.4.RELEASE
HikariCP 4.0.3 (But I think it doesn't matter lol

**Comment by gavlyukovskiy** [comment]
@Cekerel can you please send me a small sample project to reproduce the issue? Also what is the version of `p6spy-spring-boot-starter` you're using?
